### ISSUE TITLE
windows环境下是否可以搭建此平台

### ISSUE THREAD

**Issue by fengzhengzhan** [fy0/myctf#3]
报错:
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    import tornado.web
  File "C:\smallctf\2.7.10\lib\site-packages\tornado\web.py", line 205
    application: "Application",
               ^
SyntaxError: invalid syntax

系统环境：windows7服务器 python 2.7.10 使用webpy的框架运行尝试(失败)

**Comment by fy0** [comment]
可以，只是不支持python2
